#ignite-client:
#  addresses: 192.168.31.120:10800 # this is mandatory property!
#  timeout: 10000
#  tcpNoDelay: false

server:
  port: 8228

ignite:
  peerClassLoadingEnabled: true
  communicationSpi:
    localIp: localhost
    localPort: 5555
  tcpDiscoverySpi:
    ipFinder:
      type: static
      addresses:
        - "localhost:47500"